version = 1

exclude_patterns = [
  "src/main/java/org/bstats/bukkit/**"
]

test_patterns = [
    "src/test/**"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"
