name: SpectatorMode
version: ${project.version}
main: me.ohowe12.spectatormode.SpectatorMode
api-version: 1.16
softdepend: [ Multiverse-Core, LuckPerms ]
loadbefore:
  - Essentials

permissions:
  spectator.*:
    description: Give access to the entire permission node
    children:
      smpspectator.use: true
      smpspectator.enable: true
      smpspectator.speed: true
      smpspectator.bypass: true
      smpspectator.force: true
      smpspectator.toggle: true
  smpspectator.use:
    description: Be able to use the /s command
    default: op
  smpspectator.enable:
    description: Be able to enable and disable spectator mode from the /s command
    default: op
  smpspectator.speed:
    description: Be able to change fly speed in spectator mode
    default: op
  smpspectator.bypass:
    description: Be able to bypass the y-level and block restrictions
    default: op
  smpspectator.force:
    description: Be able to force other players into and out of spectator mode
    default: op
  smpspectator.toggle:
    description: Be able to use the /s effect command
    default: op
  smpspectator.reload:
    description: Be able to reload the config
    default: op

commands:
  s:
    description: The command for SMP Spectator Mode