name: SpectatorMode
version: ${project.version}
main: me.ohowe12.spectatormode.SpectatorMode
api-version: 1.16
softdepend: [ Multiverse-Core, LuckPerms, SuperVanish, GriefPrevention]
load: POSTWORLD

commands:
  s:
    description: The main command for this plugin
permissions:
  spectator.*:
    description: Give access to the entire permission node
    children:
      smpspectator.use: true
      smpspectator.enable: true
      smpspectator.bypass: true
      smpspectator.force: true
      smpspectator.toggle: true
  smpspectator.toggle:
    description: Give access to entire spectator effects permission node
    children:
      smpspectator.toggle.time: true
      smpspectator.toggle.weather: true
      smpspectator.toggle.night_vision: true
      smpspectator.toggle.conduit: true
  smpspectator.use:
    description: Be able to use the /s command
    default: op
  smpspectator.enable:
    description: Be able to enable and disable spectator mode from the /s command
    default: op
  smpspectator.bypass:
    description: Be able to bypass the y-level and block restrictions
    default: op
  smpspectator.force:
    description: Be able to force other players into and out of spectator mode
    default: op
  smpspectator.toggle.time:
    description: Allows players to manipulate the time while in spectator
    default: op
  smpspectator.toggle.weather:
    description: Allows players to manipulate the weather while in spectator
    default: op
  smpspectator.toggle.night_vision:
    description: Allows players to see in the dark while under spectator
    default: op
  smpspectator.toggle.conduit:
    description: Allows players to receive conduit while under spectator
    default: op
  smpspectator.reload:
    description: Be able to reload the config
    default: op