name: SpectatorMode
version: ${project.version}
main: me.ohowe12.spectatormode.SpectatorMode
api-version: 1.16
softdepend: [Multiverse-Core]

commands:
  s:
    description: This command will set your gamemode to spectator or survival.
  speed:
    description: Changes the flying speed in spectator mode of the player.
  seffect:
    description: This command will toggle the effects of night vision and conduit while in spectator mode

permissions:
  spectator.*:
    description: Give access to the entire permission node
    children:
      smpspectator.use: true
      smpspectator.enable: true
      smpspectator.speed: true
      smpspectator.bypass: true
      smpspectator.force: true
      smpspectator.toggle: true
  smpspectator.use:
    description: Be able to use the /s command
    default: true
  smpspectator.enable:
    description: Be able to enable and disable spectator mode from the /s command
    default: op
  smpspectator.speed:
    description: Be able to change fly speed in spectator mode
    default: true
  smpspectator.bypass:
    description: Be able to bypass the y-level and block restrictions
    default: op
  smpspectator.force:
    description: Be able to force other players into and out of spectator mode
    default: op
  smpspectator.toggle:
    description: Be able to use the /seffect command
    default: true
  smpspectator.reload:
    description: Be able to reload the config
    default: op